version: '3.1'

services:
  db:
    image: 'postgres:15.3'
    container_name: home-assistant-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home-assistant
    ports:
      - "5432:5432"